import Head from 'next/head';
import { useState } from 'react';
import { RandomFox } from '@/components/randomFox';
import { random } from '../utils/randomNumber';
export default function Home() {
	const alt: string = 'imagen aleatoria de zorro';
	const [images, setImages] = useState<string[]>([
		`https://randomfox.ca/images/${random()}.jpg`,
		`https://randomfox.ca/images/${random()}.jpg`,
		`https://randomfox.ca/images/${random()}.jpg`,
		`https://randomfox.ca/images/${random()}.jpg`,
	]);
	return (
		<>
			<Head>
				<title>React with TS</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<div>
				<main>
					<h1 className='text-4xl'>react with typescript</h1>
					{images.map((image, index) => (
						<div
							key={index}
							className='p-4'
						>
							<RandomFox
								image={image}
								alt={alt}
							/>
						</div>
					))}
				</main>
				<footer></footer>
			</div>
		</>
	);
}
