import Head from 'next/head';
import { RandomFox } from '@/components/randomFox';
import { random } from '../utils/randomNumber';
export default function Home() {
    const image: string = `https://randomfox.ca/images/${random()}.jpg`;
    const alt: string = 'imagen aleatoria de zorro';
    return (
        <>
            <Head>
                <title>React with TS</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link
                    rel='icon'
                    href='/favicon.ico'
                />
            </Head>
            <div>
                <main>
                    <h1 className='text-4xl'>react with typescript</h1>
                    <RandomFox
                        image={image}
                        alt={alt}
                    />
                </main>
                <footer></footer>
            </div>
        </>
    );
}
