import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <title>React with TS</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link
                    rel='icon'
                    href='/favicon.ico'
                />
            </Head>
            <div>
                <main>
                    <h1 className='text-4xl'>react with typescript</h1>
                </main>
                <footer></footer>
            </div>
        </>
    );
}
